CustomAuth/Controllers/RuleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DalToWeb.Models;
using DalToWeb.Repositories;

namespace CW.Controllers
{
    public class RuleController : Controller
    {
        private MainContext db = new MainContext();
        private List<object> rulesList = new List<object>()
        {
                new { Text = "1", Value = "1" },
                new { Text = "2", Value = "2" },
                new { Text = "3", Value = "3" },
        };

        // GET: Rule
        public ActionResult Index()
        {
            return View(db.Rules.OrderBy(r => r.RulePriority).ToList());
        }

        // GET: Rule/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DalToWeb.Models.Rule rule = db.Rules.Find(id);
            if (rule == null)
            {
                return HttpNotFound();
            }
            return View(rule);
        }

        // GET: Rule/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Rul = new SelectList(rulesList, "Value", "Text");
            return View();
        }

        // POST: Rule/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RuleId,RuleValue,RulePriority")] DalToWeb.Models.Rule rule)
        {
            if (ModelState.IsValid)
            {
                db.Rules.Add(rule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Rul = new SelectList(rulesList, "Value", "Text", rule.RulePriority);
            return View(rule);
        }

        // GET: Rule/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DalToWeb.Models.Rule rule = db.Rules.Find(id);
            if (rule == null)
            {
                return HttpNotFound();
            }
            ViewBag.Rul = new SelectList(rulesList, "Value", "Text", rule.RulePriority);
            return View(rule);
        }

        // POST: Rule/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RuleId,RuleValue,RulePriority")] DalToWeb.Models.Rule rule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Rul = new SelectList(rulesList, "Value", "Text", rule.RulePriority);
            return View(rule);
        }

        // GET: Rule/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DalToWeb.Models.Rule rule = db.Rules.Find(id);
            if (rule == null)
            {
                return HttpNotFound();
            }
            return View(rule);
        }

        // POST: Rule/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DalToWeb.Models.Rule rule = db.Rules.Find(id);
            db.Rules.Remove(rule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CustomAuth/Views/Rule/Create.cshtml
@model DalToWeb.Models.Rule

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RuleValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuleValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuleValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RulePriority, "Rule priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RulePriority", ViewBag.Rul as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RulePriority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CustomAuth/Views/Rule/Delete.cshtml
@model DalToWeb.Models.Rule

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RuleValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RuleValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RulePriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RulePriority)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomAuth/Views/Rule/Details.cshtml
@model DalToWeb.Models.Rule

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Rule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RuleValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RuleValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RulePriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RulePriority)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RuleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CustomAuth/Views/Rule/Edit.cshtml
@model DalToWeb.Models.Rule

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RuleId)

        <div class="form-group">
            @Html.LabelFor(model => model.RuleValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RuleValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RuleValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RulePriority, "Rule priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RulePriority", ViewBag.Rul as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RulePriority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CustomAuth/Views/Rule/Index.cshtml
@model IEnumerable<DalToWeb.Models.Rule>

@{
    ViewBag.Title = "Rules";
}

@if (User.IsInRole("Admin"))
{
    <div class="text-center">
        <a href="@Url.Action("Create", "Rule")" class="btn btn-primary">
            Add rule
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </a>
    </div>
}
   
<div class="container">
    <div class="row">
        <h2>Rules</h2>
    </div>
</div>

<div class="editor-indent" style="margin-left: 20px; padding: 0 0 0 40px; margin-right: 50px">
    @foreach (var item in Model)
    {
        var color = string.Empty;
        if (item.RulePriority == 1)
        {
            color = "#F45341";
        }
        else if (item.RulePriority == 2)
        {
            color = "#FFFFDB";
        }
        else
        {
            color = "#F2F9FF";
        }
        <table style="background-color: @color; border-radius: 10px; margin-bottom: 20px">
            <tbody>
                <tr>
                    <td style="font-size: 48px; opacity: 0.25; padding: 10px; padding-top: 15px; padding-right: 0px; vertical-align: top"><i class="fa fa-info-circle"></i></td>
                    <td >
                        <p>
                            @if (User.IsInRole("Admin"))
                            {
                                <strong>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.RuleId }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.RuleId })
                                </strong><br>
                            }
                            <ul>
                                <li>@item.RuleValue</li>
                            </ul>
                            
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>
    }
    