CustomAuth/Controllers/DocumentController.cs
using DalToWeb.Models;
using DalToWeb.Repositories;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using System.Globalization;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.SS.Util;
using System.Data;

namespace CW.Controllers
{
    public class DocumentController : Controller
    {
        private MainContext db = new MainContext();

        [NonAction]
        public int GetCurrentUserId()
        {
            var email = User.Identity.Name;
            var userId = 0;
            if (email != null)
            {
                var user = db.Users.Where(u => u.Email == email).FirstOrDefault();
                if (user != null)
                    userId = user.Id;
            }
            return userId;
        }

        [Authorize(Roles = "Admin")]
        public void GenerateExcel(int? templateId)
        {
            var template = db.LibraryReportTemplates.Find(templateId);
            if (template == null)
            {
                template = new LibraryReportTemplate()
                {
                    TemplateName = "Default",
                    PrintHeaders = false,
                    Autosized = false,
                    MaxCount = 100
                };
            }

            var lorders = db.LibraryOrders.Take(template.MaxCount).ToList();
            IWorkbook workbook;
            workbook = new XSSFWorkbook();

            ISheet sheet = workbook.CreateSheet("Library orders"); 
            
            var st = workbook.CreateCellStyle();
            st.FillForegroundColor = IndexedColors.Grey25Percent.Index;
            st.FillPattern = FillPattern.SolidForeground;

            IRow row1 = sheet.CreateRow(0);
            var columnNames = new string[] { "Status", "Title", "Count" };

            if (template.PrintHeaders)
            {
                for (int j = 0; j < 3; j++)
                {
                    ICell cell = row1.CreateCell(j);
                    String columnName = columnNames[j];
                    cell.CellStyle = st;
                    cell.SetCellValue(columnName);
                }
            }       

            for (int i = 0; i < lorders.Count; i++)
            {
                IRow row = sheet.CreateRow(i + 1);
                ICell cell = null;
                cell = row.CreateCell(0);
                var boolValue = "Inactive";
                if (lorders[i].LibraryOrderStatus)
                {
                    boolValue = "Active";
                }
                cell.SetCellValue(boolValue);
                cell = row.CreateCell(1);
                cell.SetCellValue(lorders[i].Edition.EditionTitle);
                cell = row.CreateCell(2);
                cell.SetCellValue(lorders[i].LibraryOrderCount);
            }

            if (template.Autosized)
            {
                sheet.AutoSizeColumn(0);
                sheet.AutoSizeColumn(1);
                sheet.AutoSizeColumn(2);
            }          

            using (var exportData = new MemoryStream())
            {
                Response.Clear();
                workbook.Write(exportData);
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("Content-Disposition", string.Format("attachment;filename={0}", "Library orders report.xlsx"));
                Response.BinaryWrite(exportData.ToArray());
                Response.End();
            }
        }

        // GET: Document
        [Authorize]
        public void Generate(int? templateId)
        {
            var template = db.OrderReportTemplates.Find(templateId);
            if (template == null)
            {
                template = new OrderReportTemplate()
                {
                    TemplateName = "Default",
                    PrintBackground = false,
                    PrintDayOfWeek = false,
                    PrintEditionTitle = false,
                    MaxCount = 100
                };
            }
            var userId = GetCurrentUserId();
            if (userId != 0)
            {
                var marginTop = template.PrintBackground ? 250 : 30;
                using (MemoryStream ms = new MemoryStream())
                using (Document document = new Document(PageSize.A4, 25, 25, marginTop, 30))
                using (PdfWriter writer = PdfWriter.GetInstance(document, ms))
                {
                    var orders = db.ReaderOrders
                        .Include(o => o.Exemplar)
                        .Where(o => o.UserId == userId)
                        .OrderByDescending(o => o.ReaderOrderDateOfIssue)
                        .Take(template.MaxCount)
                        .ToList();
                    var title = "Order report for " + User.Identity.Name;
                    var dateFormat = template.PrintDayOfWeek ? "D" : "d";
                    var columnCount = template.PrintEditionTitle ? 5 : 4;
                    string path = Server.MapPath(@"~/fonts/ARIALUNI.TTF");

                    iTextSharp.text.pdf.BaseFont baseFont =
                        iTextSharp.text.pdf.BaseFont.CreateFont
                        (
                            path,
                            iTextSharp.text.pdf.BaseFont.IDENTITY_H,
                            iTextSharp.text.pdf.BaseFont.NOT_EMBEDDED
                            );
                    iTextSharp.text.Font f = new iTextSharp.text.Font(baseFont, 12);
                    iTextSharp.text.Font paragraphFont = new iTextSharp.text.Font(baseFont, 20, iTextSharp.text.Font.BOLD);

                    document.Open();

                    if (template.PrintBackground)
                    {
                        iTextSharp.text.Image jpg = null;
                        string imageFilePath = Server.MapPath(@"~/images/pdf.jpg");
                        jpg = iTextSharp.text.Image.GetInstance(imageFilePath);
                        jpg.SetAbsolutePosition(0, 0);
                        jpg.ScaleToFit(600, 950);
                        jpg.Alignment = iTextSharp.text.Image.UNDERLYING;
                        document.Add(jpg);
                    }

                    var paragraph = new Paragraph(title, paragraphFont);
                    paragraph.Alignment = Element.ALIGN_CENTER;
                    paragraph.SpacingAfter = 20;
                    document.Add(paragraph);
                    PdfPTable table = new PdfPTable(columnCount);

                    PdfPCell cell = null;

                    cell = new PdfPCell(new Phrase("Order Id"));
                    cell.BackgroundColor = BaseColor.GRAY;
                    cell.HorizontalAlignment = Element.ALIGN_CENTER;
                    table.AddCell(cell);

                    cell = new PdfPCell(new Phrase("Exemplar Id"));
                    cell.BackgroundColor = BaseColor.GRAY;
                    cell.HorizontalAlignment = Element.ALIGN_CENTER;
                    table.AddCell(cell);

                    if (template.PrintEditionTitle)
                    {
                        cell = new PdfPCell(new Phrase("Edition title"));
                        cell.BackgroundColor = BaseColor.GRAY;
                        cell.HorizontalAlignment = Element.ALIGN_CENTER;
                        table.AddCell(cell);
                    }

                    cell = new PdfPCell(new Phrase("Date of issue"));
                    cell.BackgroundColor = BaseColor.GRAY;
                    cell.HorizontalAlignment = Element.ALIGN_CENTER;
                    table.AddCell(cell);

                    cell = new PdfPCell(new Phrase("Expiry date"));
                    cell.BackgroundColor = BaseColor.GRAY;
                    cell.HorizontalAlignment = Element.ALIGN_CENTER;
                    table.AddCell(cell);

                    foreach (var order in orders)
                    {
                        table.AddCell(order.ReaderOrderId.ToString());
                        table.AddCell(order.ExemplarId.ToString());
                        if (template.PrintEditionTitle)
                        {
                            table.AddCell(new Phrase(order.Exemplar.Edition.EditionTitle, f));
                        }
                        table.AddCell(order.ReaderOrderDateOfIssue.ToString(dateFormat, new CultureInfo("en-US")));
                        table.AddCell(order.ReaderOrderExpiryDate.ToString(dateFormat, new CultureInfo("en-US")));
                    }

                    document.Add(table);
                    document.Close();
                    writer.Close();
                    ms.Close();
                    Response.ContentType = "pdf/application";
                    Response.AddHeader("content-disposition", "attachment;filename=Order report.pdf");
                    Response.Cache.SetCacheability(HttpCacheability.NoCache);
                    Response.OutputStream.Write(ms.GetBuffer(), 0, ms.GetBuffer().Length);
                }
            }
            else
            {
                Response.Write("<h2>Error!</h2>");
                }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CustomAuth/Controllers/LibraryOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DalToWeb.Models;
using DalToWeb.Repositories;

namespace CW.Controllers
{
    public class LibraryOrderController : Controller
    {
        private MainContext db = new MainContext();

        // GET: LibraryOrder
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var libraryOrders = db.LibraryOrders.Include(l => l.Edition);
            return View(libraryOrders.ToList());
        }

        // GET: LibraryOrder/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LibraryOrder libraryOrder = db.LibraryOrders.Find(id);
            if (libraryOrder == null)
            {
                return HttpNotFound();
            }
            return View(libraryOrder);
        }

        // GET: LibraryOrder/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.EditionId = new SelectList(db.Editions, "EditionId", "EditionTitle");
            return View();
        }

        // POST: LibraryOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LibraryOrderId,LibraryOrderStatus,LibraryOrderCount,EditionId")] LibraryOrder libraryOrder)
        {
            if (ModelState.IsValid)
            {
                db.LibraryOrders.Add(libraryOrder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EditionId = new SelectList(db.Editions, "EditionId", "EditionTitle", libraryOrder.EditionId);
            return View(libraryOrder);
        }

        // GET: LibraryOrder/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LibraryOrder libraryOrder = db.LibraryOrders.Find(id);
            if (libraryOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.EditionId = new SelectList(db.Editions, "EditionId", "EditionTitle", libraryOrder.EditionId);
            return View(libraryOrder);
        }

        // POST: LibraryOrder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LibraryOrderId,LibraryOrderStatus,LibraryOrderCount,EditionId")] LibraryOrder libraryOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(libraryOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EditionId = new SelectList(db.Editions, "EditionId", "EditionTitle", libraryOrder.EditionId);
            return View(libraryOrder);
        }

        // GET: LibraryOrder/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LibraryOrder libraryOrder = db.LibraryOrders.Find(id);
            if (libraryOrder == null)
            {
                return HttpNotFound();
            }
            return View(libraryOrder);
        }

        // POST: LibraryOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LibraryOrder libraryOrder = db.LibraryOrders.Find(id);
            db.LibraryOrders.Remove(libraryOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CustomAuth/Views/LibraryOrder/Create.cshtml
@model DalToWeb.Models.LibraryOrder

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LibraryOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LibraryOrderStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LibraryOrderStatus)
                    @Html.ValidationMessageFor(model => model.LibraryOrderStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LibraryOrderCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LibraryOrderCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LibraryOrderCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditionId, "EditionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EditionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EditionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CustomAuth/Views/LibraryOrder/Delete.cshtml
@model DalToWeb.Models.LibraryOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LibraryOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Edition.EditionTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edition.EditionTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibraryOrderStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibraryOrderStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibraryOrderCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibraryOrderCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomAuth/Views/LibraryOrder/Details.cshtml
@model DalToWeb.Models.LibraryOrder

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LibraryOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Edition.EditionTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edition.EditionTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibraryOrderStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibraryOrderStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibraryOrderCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibraryOrderCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LibraryOrderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CustomAuth/Views/LibraryOrder/Edit.cshtml
@model DalToWeb.Models.LibraryOrder

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LibraryOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LibraryOrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.LibraryOrderStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LibraryOrderStatus)
                    @Html.ValidationMessageFor(model => model.LibraryOrderStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LibraryOrderCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LibraryOrderCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LibraryOrderCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditionId, "EditionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EditionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EditionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CustomAuth/Views/LibraryOrder/Index.cshtml
@model IEnumerable<DalToWeb.Models.LibraryOrder>

@{
    ViewBag.Title = "Library orders";
}

<h2>Library orders</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<!-- Modal -->
<div class="modal fade" id="modalDialogDocument" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Generate report</h4>

            </div>


            @using (Html.BeginForm("GenerateExcel", "Document", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label col-md-2">Choose template</label>
                        <div class="col-md-10">
                            @Html.DropDownList("templateId", ViewBag.LibraryTemplates as SelectList, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit">
                        <span class="glyphicon glyphicon-file"></span>
                        Generate
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>
<button id="modalDialogDocumentButton" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalDialogDocument">Generate report</button>
<table class="table">
    <tr>  
        <th>
            @Html.DisplayNameFor(model => model.LibraryOrderStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edition.EditionTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LibraryOrderCount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LibraryOrderStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edition.EditionTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LibraryOrderCount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LibraryOrderId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LibraryOrderId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LibraryOrderId })
        </td>
    </tr>
}

</table>